language: c++

addons:
    homebrew:
        packages:
            - glib
        update: true

    apt:
        packages:
            - build-essential
            - libglib2.0-dev
            - liblua5.1-dev
            - doxygen
            - python-epydoc
            - cmake
            - default-jdk
            - python-all-dev
            - golang

jobs:
    include:
        - name: "Ubuntu 16.04 / amd64"
          os: linux
          dist: xenial
          arch: amd64

        - name: "Ubuntu 18.04 / amd64"
          os: linux
          dist: bionic
          arch: amd64

        - name: "Ubuntu 16.04 / arm64"
          os: linux
          dist: xenial
          arch: arm64-graviton2
          virt: lxd
          group: edge

        - name: "Ubuntu 18.04 / arm64"
          os: linux
          dist: bionic
          arch: arm64-graviton2
          virt: lxd
          group: edge


script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ctest --verbose
